stages:
  - build
  - assemble-docker

build:
  image: node:alpine
  stage: build
  script:
    - npm install
    - npm run build
  tags:
  - docker

  artifacts:
    expire_in: 1 week
    paths:
     - dist

nginx-docker:
  stage: assemble-docker
  dependencies:
    - build
  script:
    - docker build -t titanic.w11k:5000/oppwa:latest
    - docker push titanic.w11k:5000/oppwa
  tags:
    - shell
